### ISSUE TITLE
ui.inflate报错Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by Pandaver** [wanZzz6/autoX-webpack-template#2]
识别成jsx了咋搞，[kkevsekk1](https://github.com/kkevsekk1/webpack-autojs)的可以正常打包
![image](https://github.com/wanZzz6/autoX-webpack-template/assets/62326552/a4751045-0a9d-4733-b139-ea09aeee0f35)

**Comment by wanZzz6** [comment]
修复了，没有对xml转义，添加了 webpack-autojs-loader 就好了

**Comment by Pandaver** [comment]
好使了谢谢

**Comment by Pandaver** [comment]
package.json里记得把javascript-obfuscator加上 @wanZzz6

**Comment by wanZzz6** [comment]
里面有 webpack-obfuscator了，会自动安装依赖javascript-obfuscator

> package.json里记得把javascript-obfuscator加上 @wanZzz6

**Comment by Pandaver** [comment]
> 里面有 webpack-obfuscator了，会自动安装依赖javascript-obfuscator
> 
> > package.json里记得把javascript-obfuscator加上 @wanZzz6

node14 environment cmd run command:
```
clone project
npm install
npm run start
```
error message:
```
...
Error: Cannot find module 'javascript-obfuscator'
...
```
add javascript-obfuscator dependency:
```
npm install javascript-obfuscator
```
npm run start success
